-- Dew — full schema setup. Paste into the Supabase SQL Editor and Run.
-- Generated by concatenating supabase/migrations/*.sql in filename order.
-- Safe to run once on a fresh project. Run supabase/seed/catalog.sql afterwards.

-- ===================================================================
-- 20260912090000_init_schema.sql
-- ===================================================================
-- DEW — initial schema (Supabase / Postgres). Phase 1 of the real-launch backend.
--
-- Relational model for the taste-graph: profiles, skin profiles, products (catalog +
-- community adds), rankings (the Shelf), ranking events + posts (the feed), daily logs,
-- routines, trials, and the follow graph. Mirrors the shapes in src/state/store.tsx so the
-- client can move from localStorage to Postgres with a thin data layer.
--
-- Security (Row-Level Security) is defined in the companion 20260912090100_security.sql —
-- RLS is enabled on every table there, so nothing is readable/writable until a policy allows it.

create extension if not exists pgcrypto;  -- gen_random_uuid()
create extension if not exists citext;    -- case-insensitive @handles

-- ------------------------------------------------------------------ enums
create type skin_type    as enum ('oily', 'dry', 'combination', 'sensitive');
create type tone         as enum ('fair', 'light', 'medium', 'tan', 'deep');
create type undertone    as enum ('warm', 'cool', 'neutral');
create type time_of_day  as enum ('am', 'pm', 'any');
create type reaction     as enum ('love', 'like', 'fine', 'dislike', 'never');
create type trial_status as enum ('active', 'completed', 'abandoned');
create type post_type    as enum ('ranking', 'trial_update', 'routine', 'recommend');

-- updated_at maintenance
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ------------------------------------------------------------------ profiles (public identity)
create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  handle       citext unique not null,
  display_name text not null default 'You',
  bio          text not null default '',
  location     text not null default '',
  avatar_url   text,
  school       text,
  member_since timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint handle_format check (handle ~ '^[a-z0-9_.]{2,24}$')
);
create trigger profiles_set_updated before update on public.profiles
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ skin profiles (SENSITIVE — owner-only)
create table public.skin_profiles (
  user_id    uuid primary key references public.profiles (id) on delete cascade,
  skin_type  skin_type,
  tone       tone,
  undertone  undertone,
  goal       text,
  interests  text[] not null default '{}',
  avoid      text[] not null default '{}',   -- ingredient ids the user reacts to
  shades     jsonb  not null default '[]',    -- self-logged cross-brand shade matches
  updated_at timestamptz not null default now()
);
create trigger skin_profiles_set_updated before update on public.skin_profiles
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ products (catalog + community adds)
create table public.products (
  id          text primary key,                 -- stable slug ('cerave-foaming-cleanser')
  brand       text not null,
  name        text not null,
  category    text not null,                    -- a categories lookup table is a fast-follow
  domain      text not null default 'skincare', -- skincare | makeup | fragrance
  price       numeric(10,2),
  time_of_day time_of_day not null default 'any',
  image_url   text,
  blurb       text,
  style_tags  text[] not null default '{}',
  is_custom   boolean not null default false,
  created_by  uuid references public.profiles (id) on delete set null,
  status      text not null default 'approved', -- community adds start 'pending' (moderation)
  created_at  timestamptz not null default now()
);
create index products_category_idx on public.products (category);
create index products_domain_idx   on public.products (domain);
create index products_created_by_idx on public.products (created_by);

-- ------------------------------------------------------------------ rankings (the Shelf)
create table public.rankings (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  product_id text not null references public.products (id) on delete cascade,
  position   double precision not null,  -- global order; fractional so reorders don't renumber
  reaction   reaction,
  strength   text,                       -- "how close?" gap to the item above (union tightened later)
  note       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, product_id)
);
create index rankings_user_idx    on public.rankings (user_id, position);
create index rankings_product_idx on public.rankings (product_id);
create trigger rankings_set_updated before update on public.rankings
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ rank events (auto feed of changes)
create table public.rank_events (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  product_id text not null references public.products (id) on delete cascade,
  category   text not null,
  from_rank  int,        -- null = newly ranked
  to_rank    int  not null,
  group_size int  not null,
  reaction   reaction,
  reason     text,
  created_at timestamptz not null default now()
);
create index rank_events_user_idx on public.rank_events (user_id, created_at desc);

-- ------------------------------------------------------------------ posts (explicit shares w/ commentary)
create table public.posts (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  type       post_type not null default 'ranking',
  product_id text references public.products (id) on delete cascade,
  tier       text,
  note       text,
  standout   text,
  created_at timestamptz not null default now()
);
create index posts_user_idx on public.posts (user_id, created_at desc);

-- ------------------------------------------------------------------ comments
create table public.comments (
  id         uuid primary key default gen_random_uuid(),
  post_id    uuid not null references public.posts (id) on delete cascade,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  body       text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);
create index comments_post_idx on public.comments (post_id, created_at);

-- ------------------------------------------------------------------ post likes
create table public.post_likes (
  post_id    uuid not null references public.posts (id) on delete cascade,
  user_id    uuid not null references public.profiles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

-- ------------------------------------------------------------------ daily logs (PRIVATE)
create table public.daily_logs (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  log_date    date not null,
  skin_rating int check (skin_rating between 0 and 4),
  note        text,
  logged      boolean not null default false,
  used_am     text[] not null default '{}',
  used_pm     text[] not null default '{}',
  updated_at  timestamptz not null default now(),
  unique (user_id, log_date)
);
create trigger daily_logs_set_updated before update on public.daily_logs
  for each row execute function public.set_updated_at();

-- ------------------------------------------------------------------ routine items (AM / PM)
create table public.routine_items (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references public.profiles (id) on delete cascade,
  period     text not null check (period in ('am', 'pm')),
  product_id text not null references public.products (id) on delete cascade,
  position   double precision not null,
  created_at timestamptz not null default now(),
  unique (user_id, period, product_id)
);
create index routine_items_user_idx on public.routine_items (user_id, period, position);

-- ------------------------------------------------------------------ trials (PRIVATE) + checkins
create table public.trials (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles (id) on delete cascade,
  product_id  text not null references public.products (id) on delete cascade,
  start_date  date not null default current_date,
  target_days int  not null default 42,
  status      trial_status not null default 'active',
  verdict     jsonb,        -- { overall:int, repurchase:bool, note:text }
  end_date    date,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index trials_user_idx on public.trials (user_id);
create trigger trials_set_updated before update on public.trials
  for each row execute function public.set_updated_at();

create table public.trial_checkins (
  id         uuid primary key default gen_random_uuid(),
  trial_id   uuid not null references public.trials (id) on delete cascade,
  check_date date not null,
  texture    int, breakouts int, dryness int, redness int,  -- -1 worse · 0 same · +1 better
  note       text,
  created_at timestamptz not null default now(),
  unique (trial_id, check_date)
);

-- ------------------------------------------------------------------ follows (the friend graph)
create table public.follows (
  follower_id uuid not null references public.profiles (id) on delete cascade,
  followee_id uuid not null references public.profiles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (follower_id, followee_id),
  constraint no_self_follow check (follower_id <> followee_id)
);
create index follows_followee_idx on public.follows (followee_id);

-- ===================================================================
-- 20260912090100_security.sql
-- ===================================================================
-- DEW — Row-Level Security. Companion to 20260912090000_init_schema.sql.
--
-- Model: the app is login-gated, so `anon` gets nothing; `authenticated` gets table privileges
-- but every row is still gated by the policies below.
--   • You always have full control of your own rows.
--   • Followers can READ your shelf / feed / routines (the social graph) but never write them.
--   • Skin profiles, daily logs, and trials are PRIVATE (owner-only) — sensitive skin data.
--   • The product catalog is readable by everyone signed in; community adds are owner-editable
--     and start life as 'pending' for moderation.

-- ------------------------------------------------------------------ visibility helper
-- SECURITY DEFINER so it can read follows without tripping that table's own RLS (and to avoid
-- recursive policy evaluation). Returns true if the current user follows `target`.
create or replace function public.is_following(target uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.follows
    where follower_id = auth.uid() and followee_id = target
  );
$$;

-- ------------------------------------------------------------------ table privileges (RLS still applies)
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;
alter default privileges in schema public
  grant select, insert, update, delete on tables to authenticated;

-- ------------------------------------------------------------------ enable RLS everywhere
alter table public.profiles       enable row level security;
alter table public.skin_profiles  enable row level security;
alter table public.products       enable row level security;
alter table public.rankings       enable row level security;
alter table public.rank_events    enable row level security;
alter table public.posts          enable row level security;
alter table public.comments       enable row level security;
alter table public.post_likes     enable row level security;
alter table public.daily_logs     enable row level security;
alter table public.routine_items  enable row level security;
alter table public.trials         enable row level security;
alter table public.trial_checkins enable row level security;
alter table public.follows        enable row level security;

-- ------------------------------------------------------------------ profiles (public identity)
create policy profiles_read   on public.profiles for select to authenticated using (true);
create policy profiles_insert on public.profiles for insert to authenticated with check (id = auth.uid());
create policy profiles_update on public.profiles for update to authenticated
  using (id = auth.uid()) with check (id = auth.uid());

-- ------------------------------------------------------------------ skin profiles (PRIVATE)
create policy skin_owner on public.skin_profiles for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ------------------------------------------------------------------ products (catalog + community adds)
create policy products_read on public.products for select to authenticated
  using (status = 'approved' or created_by = auth.uid());
create policy products_insert on public.products for insert to authenticated
  with check (created_by = auth.uid() and is_custom = true);
create policy products_update on public.products for update to authenticated
  using (created_by = auth.uid()) with check (created_by = auth.uid());
create policy products_delete on public.products for delete to authenticated
  using (created_by = auth.uid());

-- ------------------------------------------------------------------ rankings (you + people you follow)
create policy rankings_read on public.rankings for select to authenticated
  using (user_id = auth.uid() or public.is_following(user_id));
create policy rankings_write on public.rankings for insert to authenticated
  with check (user_id = auth.uid());
create policy rankings_update on public.rankings for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy rankings_delete on public.rankings for delete to authenticated
  using (user_id = auth.uid());

-- ------------------------------------------------------------------ rank events (feed)
create policy rank_events_read on public.rank_events for select to authenticated
  using (user_id = auth.uid() or public.is_following(user_id));
create policy rank_events_write on public.rank_events for insert to authenticated
  with check (user_id = auth.uid());

-- ------------------------------------------------------------------ posts (feed)
create policy posts_read on public.posts for select to authenticated
  using (user_id = auth.uid() or public.is_following(user_id));
create policy posts_write on public.posts for insert to authenticated
  with check (user_id = auth.uid());
create policy posts_update on public.posts for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy posts_delete on public.posts for delete to authenticated
  using (user_id = auth.uid());

-- ------------------------------------------------------------------ comments (visible if you can see the post)
create policy comments_read on public.comments for select to authenticated
  using (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.user_id = auth.uid() or public.is_following(p.user_id))
  ));
create policy comments_write on public.comments for insert to authenticated
  with check (user_id = auth.uid() and exists (
    select 1 from public.posts p
    where p.id = post_id and (p.user_id = auth.uid() or public.is_following(p.user_id))
  ));
create policy comments_delete on public.comments for delete to authenticated
  using (user_id = auth.uid());

-- ------------------------------------------------------------------ post likes
create policy post_likes_read on public.post_likes for select to authenticated
  using (exists (
    select 1 from public.posts p
    where p.id = post_id and (p.user_id = auth.uid() or public.is_following(p.user_id))
  ));
create policy post_likes_write on public.post_likes for insert to authenticated
  with check (user_id = auth.uid());
create policy post_likes_delete on public.post_likes for delete to authenticated
  using (user_id = auth.uid());

-- ------------------------------------------------------------------ daily logs (PRIVATE)
create policy daily_logs_owner on public.daily_logs for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- ------------------------------------------------------------------ routine items (you + followers read)
create policy routine_read on public.routine_items for select to authenticated
  using (user_id = auth.uid() or public.is_following(user_id));
create policy routine_write on public.routine_items for insert to authenticated
  with check (user_id = auth.uid());
create policy routine_update on public.routine_items for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy routine_delete on public.routine_items for delete to authenticated
  using (user_id = auth.uid());

-- ------------------------------------------------------------------ trials + checkins (PRIVATE)
create policy trials_owner on public.trials for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
create policy trial_checkins_owner on public.trial_checkins for all to authenticated
  using (exists (select 1 from public.trials t where t.id = trial_id and t.user_id = auth.uid()))
  with check (exists (select 1 from public.trials t where t.id = trial_id and t.user_id = auth.uid()));

-- ------------------------------------------------------------------ follows (public graph)
create policy follows_read on public.follows for select to authenticated using (true);
create policy follows_write on public.follows for insert to authenticated
  with check (follower_id = auth.uid());
create policy follows_delete on public.follows for delete to authenticated
  using (follower_id = auth.uid());

-- ------------------------------------------------------------------ auto-create a profile on signup
-- New auth user → a profiles row with a guaranteed-valid, unique placeholder @handle the user
-- customizes during onboarding. Google gives us name + avatar in user metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, handle, display_name, avatar_url)
  values (
    new.id,
    'dew' || substr(replace(new.id::text, '-', ''), 1, 10),
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', 'You'),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ===================================================================
-- 20260916120000_onboarding.sql
-- ===================================================================
-- Onboarding: mark completion on the profile, and store the extra quiz fields on skin_profiles.
alter table public.profiles add column if not exists onboarded boolean not null default false;
alter table public.skin_profiles add column if not exists budget text;
alter table public.skin_profiles add column if not exists depth text;

