// AUTO-GENERATED by scripts/obf-match, then MANUALLY VERIFIED (each photo was eyeballed against
// the product before inclusion). Real product photos sourced from Open Beauty Facts
// (https://openbeautyfacts.org) — an open, crowd-sourced database (data under the Open Database
// License; images under their per-photo licenses).
//
// Correctness over coverage: of the exact brand + exact-name candidates OBF returned, only the
// ones whose front-label photo unambiguously matched the product were kept. Everything uncertain,
// wrong-variant, or unreadable kept its polished placeholder (see obf-curation.md for the audit).
//
// Consulted ONLY as a last resort in lib/productImages.ts, so it never overrides a manually set
// `image` field or a bundled asset in src/assets/products.
export const OBF_IMAGES: Record<string, string> = {
  // Drunk Elephant — Lala Retro Whipped Cream (white jar, lavender lid — verified)
  'de-lala': 'https://images.openbeautyfacts.org/images/products/200/000/015/1852/front_en.3.400.jpg',
  // Kiehl's — Creamy Eye Treatment with Avocado (labelled white jar — verified)
  'kiehls-avocado-eye': 'https://images.openbeautyfacts.org/images/products/370/019/471/4413/front_en.3.400.jpg',
  // ILIA — Limitless Lash Mascara (cream ILIA tube — verified)
  'ilia-limitless-mascara': 'https://images.openbeautyfacts.org/images/products/200/000/015/1846/front_en.3.400.jpg',
};
